### ISSUE TITLE
Move this repository under another account

### ISSUE THREAD

**Issue by zonca** [openEXO/cloud-kepler#64]
@scfleming we haven't been using the `openExo` organization in a while.
What about moving `cloud-kepler` to your user account (possibly archive it) and close the organization?

**Comment by scfleming** [comment]
Could do that, do you know if someone would like to use this org. name for something?  I'd want to check with Peter first before moving the repo, but don't think he'd have strong opinions either way. Thanks!

**Comment by zonca** [comment]
Yes, @erseco asked me if he can use it for his startup

**Comment by erseco** [comment]
Yes, we are a small Spanish startup previously called @exolever. We are focused in the Exponential Organizations metodologhy. We decide to opensource and rebrand our startup to `openexo`, thats why I asked @zonca to transfer the ownership of the organization, actually we have the domain www.openexo.com and we want to transfer all our source code to @openexo.
Thanks for your help!

**Comment by scfleming** [comment]
Understood, once the Principal Investigator approves I have no problem moving the repo and retiring this organization, please stay tuned.

**Comment by erseco** [comment]
Hi guys! finally, did you take any decision about moving the repository?

Best!

**Comment by erseco** [comment]
Hi @zonca and @scfleming I speak with @ivanmladek about the transfer but we can't pay that amount of money (9.000$) so we will release our code via @open-exo

Thanks for your time and best regards!

**Comment by scfleming** [comment]
OK thanks, glad you found a solution.

**Comment by zonca** [comment]
I removed myself from the organization, do not need to be a member anymore.
